/*
    COLLISIONS_TILES.H
    Generated by gb_map_converter v1.2.
*/

#ifndef __MAP_COLLISIONS_TILES_H__
#define __MAP_COLLISIONS_TILES_H__

#define COLLISIONS_TILE_COUNT 2

#define COLLISIONS_PALETTE 0xFB

extern const void __bank_COLLISIONS_TILE_DATA;

extern const unsigned char COLLISIONS_TILE_DATA[];

#endif
